/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DemoList {
    }
    interface VirtualizedList {
        "items": any[];
        "renderRow"?: (item: (typeof this.items)[0]) => HTMLElement;
    }
}
declare global {
    interface HTMLDemoListElement extends Components.DemoList, HTMLStencilElement {
    }
    var HTMLDemoListElement: {
        prototype: HTMLDemoListElement;
        new (): HTMLDemoListElement;
    };
    interface HTMLVirtualizedListElement extends Components.VirtualizedList, HTMLStencilElement {
    }
    var HTMLVirtualizedListElement: {
        prototype: HTMLVirtualizedListElement;
        new (): HTMLVirtualizedListElement;
    };
    interface HTMLElementTagNameMap {
        "demo-list": HTMLDemoListElement;
        "virtualized-list": HTMLVirtualizedListElement;
    }
}
declare namespace LocalJSX {
    interface DemoList {
    }
    interface VirtualizedList {
        "items"?: any[];
        "renderRow"?: (item: (typeof this.items)[0]) => HTMLElement;
    }
    interface IntrinsicElements {
        "demo-list": DemoList;
        "virtualized-list": VirtualizedList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "demo-list": LocalJSX.DemoList & JSXBase.HTMLAttributes<HTMLDemoListElement>;
            "virtualized-list": LocalJSX.VirtualizedList & JSXBase.HTMLAttributes<HTMLVirtualizedListElement>;
        }
    }
}
